databases:
  - name: microverse
    databaseName: microverse_f3bw
    user: microverse_f3bw_user

services:
  - type: web
    name: Budget-apppp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microverse
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false